title: "Website"
name: "Marco Leali"
description: "Researcher in Machine Learning and NLP"

url: "https://lealimarco.github.io"

markdown: kramdown

author:
  name: "Marco Leali"
  avatar: "/images/pic.heic"
  bio: "Researcher in ML, NLP and Human-AI interaction"
  location: "Sweden"
  email: "lealimarco@hotmail.it"

social:
  github: https://github.com/lealimarco
  linkedin: https://www.linkedin.com/in/lealimarco/